server:
  port: 8200
spring:
  application:
    name: github-weixin
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
swagger:
  base-package: com.github.service.impl
  title: shop-github-wecharservice-interface
  description: authon pengliang
  version: 1.0
  terms-of-service-url: com.github.pengliang
  contact:
    email: 247938189@qq.com
    name: penglaing
