server:
  port: 80
spring:
  application:
    name: github-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
zuul:
  routes:
    api-a:
      path: /api-weixin/**
      serviceId: github-weixin
    api-b:
      path: /api-member/**
      serviceId: github-member